### ISSUE TITLE
[Python] Вопрос к знатокам на тоненького

### ISSUE THREAD

**Issue by evvfebruary** [buzyakabarbuzyaka/djtest#3]
https://github.com/buzyakabarbuzyaka/djtest/blob/14acafaa1ec162f17d5306638738db64220200e8/requirements.txt#L1

Смотри у тебя тут есть оператор ```~=``` в чем его отличие от оператора ```==``` ? Какие версии пакета поставит ```pip``` в одном и другом случае при использование ```pip -r requirements.txt```

**Comment by buzyakabarbuzyaka** [comment]
[Здесь описаны все операторы](https://www.python.org/dev/peps/pep-0440/#version-matching)
== точное равенство версий, поддерживает *
~= то же что и (>=A.B.C, ==A.B.*) тоесть меняется только суффикс в большую сторону
=== точное равентсво строк-спецификаторов версий
